### ISSUE TITLE
Some recipe sources force the app to crash.

### ISSUE THREAD

**Issue by smappinc** [haerulmuttaqin/FoodsApp-starting-code#3]
As you can see in the GIF below, while navigating to Desert then to one of the recipes, the app crashes.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/46318200/56123116-7ed54400-5f7c-11e9-8b88-481306fe6249.gif)

**Comment by haerulmuttaqin** [comment]
check the intent put extra

**Comment by dzakdzaks** [comment]
because in https://www.themealdb.com/api/json/v1/1/search.php?s=Apple%20Frangipan%20Tart the value of strSource, some ingredient and measure have a null value.

**Comment by dzakdzaks** [comment]
@smappinc just change the if to  
if (meal.getStrMeasure16() != null && !meal.getStrMeasure16().isEmpty() && !Character.isWhitespace(meal.getStrMeasure16().charAt(0))) {
            measures.append("\n : " + meal.getStrMeasure16());
        }

add meal.getStrMeasure16() != null  every single ingredient and measure. also youtube and source

it works like a charm..

**Comment by fandi70** [comment]
Button ic_favorite not work in tutorial, there are applications in there.

**Comment by fandi70** [comment]
In PlayStore

**Comment by HeshanHH** [comment]
everything working fine **BUT when i click on meal the category does not load. please help.**

**Comment by sushen** [comment]
@HeshanHH I am facing the same problem. I am using a postman for JSON formatting except that everything is the same. I can't find out where the problem comes from.

**Comment by sushen** [comment]
I miss understood there is no problem in code.
See my complete project.
https://github.com/sushen/FoodsApp-starting-code?organization=sushen&organization=sushen

**Comment by rogergcc** [comment]
**in Model Meal**

```
        @SerializedName("strIngredient16")
        @Nullable
        @Expose
        private String strIngredient16;
```

**and in DetailActivity autocomplete with**

```
 if (meal.getStrIngredient16() != null && !meal.getStrIngredient16().isEmpty()) {
            ingredients.append("\n \u2022 " + meal.getStrIngredient16());
        }
```
and this for each property :).
if there is a better way pls comment

**Comment by haerulmuttaqin** [comment]
https://github.com/haerulmuttaqin/FoodsApp-starting-code/issues/3#issuecomment-557198374
